# -*- coding: utf-8 -*-
"""Calculadora

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L6BewXsdwhABMJCrojcH2IFOLs8PuntY

Criar uma Calculadora:
"""

def calculadora(x, y):
  print('soma - ', x + y)
  print('subração - ', x - y)
  print('divisão - ', x / y)
  print('multiplicação -', x * y)

calculadora(6, 3)